package mojServis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-01-19T00:33:50.950+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "KonfWebService", 
                  wsdlLocation = "http://localhost:8080/Konf2EJB/KonfWeb?WSDL",
                  targetNamespace = "http://beans/") 
public class KonfWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://beans/", "KonfWebService");
    public final static QName KonfWebPort = new QName("http://beans/", "KonfWebPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Konf2EJB/KonfWeb?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KonfWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Konf2EJB/KonfWeb?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public KonfWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KonfWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KonfWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public KonfWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KonfWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KonfWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns KonfWebRemote
     */
    @WebEndpoint(name = "KonfWebPort")
    public KonfWebRemote getKonfWebPort() {
        return super.getPort(KonfWebPort, KonfWebRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KonfWebRemote
     */
    @WebEndpoint(name = "KonfWebPort")
    public KonfWebRemote getKonfWebPort(WebServiceFeature... features) {
        return super.getPort(KonfWebPort, KonfWebRemote.class, features);
    }

}
