package mojServis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-01-19T00:33:50.887+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://beans/", name = "KonfWebRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface KonfWebRemote {

    @WebMethod
    @RequestWrapper(localName = "getKonferencije", targetNamespace = "http://beans/", className = "mojServis.GetKonferencije")
    @ResponseWrapper(localName = "getKonferencijeResponse", targetNamespace = "http://beans/", className = "mojServis.GetKonferencijeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<mojServis.Conference> getKonferencije(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
