package javni;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-01-18T23:54:29.228+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "countryHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CountryHttpPost {

    /**
     * Get all currency,currency code for all countries 
     */
    @WebMethod(operationName = "GetCurrencies")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCurrencies();

    /**
     * Get International Dialing Code by country name 
     */
    @WebMethod(operationName = "GetISD")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getISD(
        @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String countryName
    );

    /**
     * Get country by currency code
     */
    @WebMethod(operationName = "GetCountryByCurrencyCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCountryByCurrencyCode(
        @WebParam(partName = "CurrencyCode", name = "CurrencyCode", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String currencyCode
    );

    /**
     * Get countries by country name 
     */
    @WebMethod(operationName = "GetISOCountryCodeByCountyName")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getISOCountryCodeByCountyName(
        @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String countryName
    );

    /**
     * Get all currencycode for each country 
     */
    @WebMethod(operationName = "GetCurrencyCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCurrencyCode();

    /**
     * Get currency by country name 
     */
    @WebMethod(operationName = "GetCurrencyByCountry")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCurrencyByCountry(
        @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String countryName
    );

    /**
     * Get all countries with ISO code
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCountries();

    /**
     * Get currency by currency name 
     */
    @WebMethod(operationName = "GetCurrencyCodeByCurrencyName")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCurrencyCodeByCurrencyName(
        @WebParam(partName = "CurrencyName", name = "CurrencyName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String currencyName
    );

    /**
     * Get greenwich mean time(GMT) by country name 
     */
    @WebMethod(operationName = "GetGMTbyCountry")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getGMTbyCountry(
        @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String countryName
    );

    /**
     * Get country name by country code
     */
    @WebMethod(operationName = "GetCountryByCountryCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getCountryByCountryCode(
        @WebParam(partName = "CountryCode", name = "CountryCode", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String countryCode
    );
}
